apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-percona-manager
rules:
- apiGroups: ["pgv2.percona.com"]
  resources: ["perconapgclusters", "perconapgbackups", "perconapgrestores", "perconapgupgrades"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["pgv2.percona.com"]
  resources: ["perconapgclusters/status", "perconapgbackups/status", "perconapgrestores/status", "perconapgupgrades/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["psmdb.percona.com"]
  resources: ["perconaservermongodbs", "perconaservermongodbbackups", "perconaservermongodbrestores"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["psmdb.percona.com"]
  resources: ["perconaservermongodbs/status", "perconaservermongodbbackups/status", "perconaservermongodbrestores/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["pxc.percona.com"]
  resources: ["perconaxtradbclusters", "perconaxtradbclusterbackups", "perconaxtradbclusterrestores"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["pxc.percona.com"]
  resources: ["perconaxtradbclusters/status", "perconaxtradbclusterbackups/status", "perconaxtradbclusterrestores/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-percona-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-percona-manager
subjects:
- kind: ServiceAccount
  name: crossplane
  namespace: crossplane
