apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: my_database
spec:
  version: "6.0"
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  databaseSecret:
    secretName: my-mongo-db-auth 