---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mimir-dataservice
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - mimir.siliconsaga.org
  resources:
  - dataservices
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mimir.siliconsaga.org
  resources:
  - dataservices/finalizers
  verbs:
  - update
- apiGroups:
  - mimir.siliconsaga.org
  resources:
  - dataservices/status
  verbs:
  - get
  - patch
  - update
